### PR TITLE
chore: move sign_document.js file from bloomstack_core to erpnext

### PR DESCRIPTION
**Pull request by meshramsaroj**
**Related PR:** https://github.com/Bloomstack/erpnext/pull/1642

### CODE REVIEW

**Review by sahil28297 — COMMENTED** [review]
https://github.com/Bloomstack/erpnext/pull/1641#pullrequestreview-753807057

**Review by sahil28297 — CHANGES_REQUESTED** [review]
https://github.com/Bloomstack/erpnext/pull/1642#pullrequestreview-753812593

**Comment by meshramsaroj** [comment]
> [Bloomstack/erpnext#1642 (review)](https://github.com/Bloomstack/erpnext/pull/1642#pullrequestreview-753812593)

resolved mentioned comments

**Review by sahil28297 — COMMENTED** [review]
@meshramsaroj remove the item.js and hooks.py changes from this PR

**Comment by meshramsaroj** [comment]
> @meshramsaroj remove the item.js and hooks.py changes from this PR

Removed  item.js and hooks.py file from PR

**Review by sahil28297 — APPROVED** [review]

**Pull request merged**
