### PR TITLE
Fix cheque with remittance

### PR DESCRIPTION
**Pull request by meshramsaroj**
**Description:** Fixed naming issue like cheque -> check

**Screenshot:** 

- Before:
image

- After:
image

### CODE REVIEW

**Comment by vishdha** [comment]
@meshramsaroj Change the base branch to develop

**Review by vishdha — COMMENTED** [review]
@meshramsaroj change base branch to develop

**Comment by vishdha** [comment]
@meshramsaroj  Rebase with develop

**Review by nehasacher143 — CHANGES_REQUESTED** [review]
@meshramsaroj Please do the changes mentioned by @vishdha 
Apart from that looks fine to me

**Review by hrwX — APPROVED** [review]

**Pull request merged**
